// Comprehensive Data Broker Database
const dataBrokers = [
    { id: 'whitepages', name: 'Whitepages', url: 'https://www.whitepages.com', optOutUrl: 'https://www.whitepages.com/suppression-requests', category: 'People Search', difficulty: 'Medium', estimatedTime: '24 hours', instructions: 'Search for your listing, copy the URL, then submit it via the opt-out form. Verification may be required.', notes: 'Owned by Hometownstation Media. May require ID verification.' },
    { id: 'spokeo', name: 'Spokeo', url: 'https://www.spokeo.com', optOutUrl: 'https://www.spokeo.com/optout', category: 'People Search', difficulty: 'Easy', estimatedTime: '72 hours', instructions: 'Search for yourself, find your listing, and submit the opt-out form with the listing URL.', notes: 'Email verification required. Check spam folder for confirmation.' },
    { id: 'peoplefinder', name: 'PeopleFinder', url: 'https://www.peoplefinder.com', optOutUrl: 'https://www.peoplefinder.com/optout', category: 'People Search', difficulty: 'Easy', estimatedTime: '48 hours', instructions: 'Enter your information in the opt-out form. Email confirmation will be sent.', notes: 'Part of Confi-Chek network. Relatively quick removal process.' },
    { id: 'beenverified', name: 'BeenVerified', url: 'https://www.beenverified.com', optOutUrl: 'https://www.beenverified.com/app/optout/search', category: 'Background Check', difficulty: 'Medium', estimatedTime: '7 days', instructions: 'Find your record, then submit opt-out request with the record URL.', notes: 'May take up to 7 days. Keep confirmation email.' },
    { id: 'intelius', name: 'Intelius', url: 'https://www.intelius.com', optOutUrl: 'https://www.intelius.com/optout', category: 'Background Check', difficulty: 'Hard', estimatedTime: '72 hours', instructions: 'Requires phone verification. Submit form with your information and verify via SMS.', notes: 'Owns PeopleLookup, DateCheck, iSearch, PublicRecordsNow, Addresses.' },
    { id: 'truthfinder', name: 'TruthFinder', url: 'https://www.truthfinder.com', optOutUrl: 'https://www.truthfinder.com/opt-out/', category: 'Background Check', difficulty: 'Medium', estimatedTime: '48 hours', instructions: 'Search for your profile, then fill out opt-out form with profile URL.', notes: 'Email confirmation required. May need to opt out of multiple profiles.' },
    { id: 'mylife', name: 'MyLife', url: 'https://www.mylife.com', optOutUrl: 'https://www.mylife.com/privacy-policy', category: 'Reputation Management', difficulty: 'Hard', estimatedTime: '7-10 days', instructions: 'Create account, claim profile, then request removal via customer support.', notes: 'Known for being difficult. May require multiple attempts.' },
    { id: 'radaris', name: 'Radaris', url: 'https://radaris.com', optOutUrl: 'https://radaris.com/page/how-to-remove', category: 'People Search', difficulty: 'Medium', estimatedTime: '72 hours', instructions: 'Search for yourself, find all listings, submit opt-out for each one.', notes: 'May have multiple profiles. Check all variations of your name.' },
    { id: 'fastpeoplesearch', name: 'FastPeopleSearch', url: 'https://www.fastpeoplesearch.com', optOutUrl: 'https://www.fastpeoplesearch.com/removal', category: 'People Search', difficulty: 'Easy', estimatedTime: '24 hours', instructions: 'Find your listing, click "remove this record", complete CAPTCHA.', notes: 'One of the easier removals. Fast processing time.' },
    { id: 'thatsthem', name: 'ThatsThem', url: 'https://thatsthem.com', optOutUrl: 'https://thatsthem.com/optout', category: 'People Search', difficulty: 'Easy', estimatedTime: '48 hours', instructions: 'Search for your info, click opt-out link on your profile page.', notes: 'Straightforward process. Email confirmation sent.' },
    { id: 'ussearch', name: 'USSearch', url: 'https://www.ussearch.com', optOutUrl: 'https://www.ussearch.com/opt-out/submit/', category: 'People Search', difficulty: 'Medium', estimatedTime: '5-7 days', instructions: 'Find your listing, submit opt-out form with listing URL.', notes: 'Related to PeopleFinders. May need separate opt-out.' },
    { id: 'nuwber', name: 'Nuwber', url: 'https://nuwber.com', optOutUrl: 'https://nuwber.com/removal/link', category: 'People Search', difficulty: 'Medium', estimatedTime: '72 hours', instructions: 'Find your profile, click opt-out, verify via email link.', notes: 'Email verification required. Check spam folder.' },
    { id: 'checkpeople', name: 'CheckPeople', url: 'https://www.checkpeople.com', optOutUrl: 'https://www.checkpeople.com/do-not-sell', category: 'Background Check', difficulty: 'Medium', estimatedTime: '48 hours', instructions: 'Submit opt-out form with your details. Email confirmation required.', notes: 'Part of InfoPay network.' },
    { id: 'peekyou', name: 'PeekYou', url: 'https://www.peekyou.com', optOutUrl: 'https://www.peekyou.com/about/contact/ccpa_optout/', category: 'People Search', difficulty: 'Easy', estimatedTime: '24-48 hours', instructions: 'Fill out CCPA opt-out form with your information.', notes: 'CCPA compliant. Relatively quick removal.' },
    { id: 'truepeoplesearch', name: 'TruePeopleSearch', url: 'https://www.truepeoplesearch.com', optOutUrl: 'https://www.truepeoplesearch.com/removal', category: 'People Search', difficulty: 'Easy', estimatedTime: '24 hours', instructions: 'Search for your listing, click remove button, complete verification.', notes: 'Fast removal process. Email confirmation sent.' },
    { id: 'instantcheckmate', name: 'Instant Checkmate', url: 'https://www.instantcheckmate.com', optOutUrl: 'https://www.instantcheckmate.com/opt-out/', category: 'Background Check', difficulty: 'Hard', estimatedTime: '10-15 days', instructions: 'Find your profile, submit opt-out with government-issued ID.', notes: 'Requires ID verification. One of the more difficult removals.' },
    { id: 'privateeye', name: 'PrivateEye', url: 'https://www.privateeye.com', optOutUrl: 'https://www.privateeye.com/static/view/optout/', category: 'Background Check', difficulty: 'Medium', estimatedTime: '5-7 days', instructions: 'Submit opt-out request form with personal details.', notes: 'Email verification required.' },
    { id: 'peoplefinders', name: 'PeopleFinders', url: 'https://www.peoplefinders.com', optOutUrl: 'https://www.peoplefinders.com/opt-out', category: 'People Search', difficulty: 'Medium', estimatedTime: '48-72 hours', instructions: 'Locate your listing, submit opt-out form with listing URL.', notes: 'May require multiple submissions for different listings.' },
    { id: 'advancedbackgroundchecks', name: 'Advanced Background Checks', url: 'https://www.advancedbackgroundchecks.com', optOutUrl: 'https://www.advancedbackgroundchecks.com/removal', category: 'Background Check', difficulty: 'Easy', estimatedTime: '24-48 hours', instructions: 'Complete online opt-out form with your information.', notes: 'Simple removal process.' },
    { id: 'clustrmaps', name: 'Clustrmaps', url: 'https://clustrmaps.com', optOutUrl: 'https://clustrmaps.com/bl/opt-out', category: 'Address/Location', difficulty: 'Easy', estimatedTime: '24 hours', instructions: 'Enter address to search, then request removal.', notes: 'Focused on property/address information.' },
    { id: 'familytreenow', name: 'Family Tree Now', url: 'https://www.familytreenow.com', optOutUrl: 'https://www.familytreenow.com/optout', category: 'Genealogy', difficulty: 'Medium', estimatedTime: '48 hours', instructions: 'Search for your profile, submit opt-out with profile URL.', notes: 'May show family connections. Privacy-focused removal.' },
    { id: 'neighborwho', name: 'NeighborWho', url: 'https://www.neighborwho.com', optOutUrl: 'https://www.neighborwho.com/remove', category: 'Address/Location', difficulty: 'Easy', estimatedTime: '2 hours', instructions: 'Search by address, find your listing, click remove.', notes: 'Very fast removal. One of the quickest.' },
    { id: 'addresses', name: 'Addresses.com', url: 'https://www.addresses.com', optOutUrl: 'https://www.addresses.com/optout.php', category: 'Address/Location', difficulty: 'Medium', estimatedTime: '72 hours', instructions: 'Search for your listing, submit opt-out form.', notes: 'Owned by Intelius. May need to opt out of Intelius too.' },
    { id: 'cyberbackgroundchecks', name: 'Cyber Background Checks', url: 'https://www.cyberbackgroundchecks.com', optOutUrl: 'https://www.cyberbackgroundchecks.com/removal', category: 'Background Check', difficulty: 'Easy', estimatedTime: '48 hours', instructions: 'Fill out removal request form with your details.', notes: 'Straightforward opt-out process.' },
    { id: 'publicdatausa', name: 'PublicDataUSA', url: 'https://www.publicdatausa.com', optOutUrl: 'https://www.publicdatausa.com/opt-out.php', category: 'Public Records', difficulty: 'Medium', estimatedTime: '5-7 days', instructions: 'Find your record, submit opt-out with record URL and email.', notes: 'May have multiple records to remove.' },
    { id: 'zabasearch', name: 'ZabaSearch', url: 'https://www.zabasearch.com', optOutUrl: 'https://www.zabasearch.com/block_records/', category: 'People Search', difficulty: 'Hard', estimatedTime: '7-14 days', instructions: 'Must send written request via postal mail with ID copy.', notes: 'Requires physical mail. One of the most difficult.' }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = dataBrokers;
}
